### ISSUE TITLE
Twitter API support

### ISSUE THREAD

**Issue by MariaArtemis** [dheerajpv/pfpet#4]
I looked into the possibility of adding Twitter to the list of possible petting endpoints, but Twitter is quite increasingly hostile to webscraping, so that doesn't seem to be a possibility. 

I could go do this kind of stuff through the Twitter API, but that requires me getting developer keys and then maintainer will be forced to make a developer account and then also require anyone hosting this to get devkeys aswell.... not fun.

What do you think about adding twitter support? What else could receive endpoint support?

**Comment by ariscript** [comment]
Twitter stopped offering user avatars through a public API in 2020. The only way to get it now would be through reverse engineering private APIs or scraping the user page, neither of which is really a good idea. So unless Twitter changes that in the future (which they probably won't), I don't really see a good way to add Twitter user avatars.

But as for other platforms, as long as there's a public API that takes in a username/ID and provides a way to get an image, it can be implemented.

**Comment by MariaArtemis** [comment]
I'll be looking into which places lets us get the profile picture easily.
